### ISSUE TITLE
Conduct analysis and implement memory usage improvements

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#123]
When triggering DAGs for larger multi-collection data providers, some tasks are failing because of memory constraints `This containers encounter an error during launching : outofmemoryerror: container killed due to memory usage`. There may be areas where our code can be improved to use memory more efficiently. We should implement these improvement where it makes sense to do so. We may also need to increase the memory of the containers.

**Comment by aaron-collier** [comment]
Analysis in review by Ops/Access. Closing.
