### ISSUE TITLE
Add catalog validation

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#132]
As the DLME data manager, I need to ensure that all catalogs are valid and complete when I add them. The catalog model has changed since it was first implemented, though all catalogs have not been updated. It is easy for old catalogs to get out of date. It is also unclear which fields are required for which intake driver. This should all be specified in an external validation (e.g. like Dry validation for DLME transform traject configs). The validation should specify whether a field is required or optional. It should include comments for unusual fields so that it is clear what they do and when they should be added. It should include a way of testing locally before starting airflow to ensure that all catalogs are complete and valid.

**Comment by aaron-collier** [comment]
This may be best handled as a unit test following something like: https://stackoverflow.com/questions/3262569/validating-a-yaml-document-in-python

This will require a schema be developed that can be used for the test.

**Comment by aaron-collier** [comment]
This is complete.
