### ISSUE TITLE
Add post harvest step to fetch penn museum thumbnails

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#158]
There is some code that probably works but needs cleanup [here](https://github.com/sul-dlss/dlme-harvest/blob/master/deprecated/harvest-scripts/penn-museum-harvest.py)

**Comment by edsu** [comment]
@aaron-collier Is a reasonable approach for this to have the post harvest step look at the URL in the harvested CSV and add a `thumbnail` column based on what it can find in the HTML of the page?

**Comment by edsu** [comment]
I noticed that the item pages have some embedded JSON-LD that includes the thumbnail, which would be potentially reusable on other sites? e.g. https://www.penn.museum/collections/object/15390

```json
{
  "@context": "http://schema.org/",
  "@type": "CreativeWork",
  "url": "https://www.penn.museum/collections/object/15390",
  "description": "Bronze. From a hoard found in a jar (32-42-1167). The following are represented: Constans, Arcadius, Theodosius, Honorius, Valentinian, Gratian, Magn. Maximus, Julian, Helene, Aelia Flacilla.",
  "identifier": "32-42-1200.1689",
  "name": "Coin",
  "material": "Bronze",
  "thumbnailUrl": "https://www.penn.museum/collections/assets/327554_800.jpg",
  "dateModified": "2021-09-20T14:34:50+00:00"
}
```

**Comment by jacobthill** [comment]
@edsu that sounds reasonable to me.
