### ISSUE TITLE
Command line utility for getting provider data

### ISSUE THREAD

**Issue by edsu** [sul-dlss/dlme-airflow#205]
When working with a provider it can sometimes be tedious to have to wait for a harvest to finish in Airflow to see the effects of changing an intake catalog entry, or developing a Traject configuration. This is especially problematic when one URL out of many fails to fetch, which then causes the entire DataFrame generation and CSV output to fail. This use case was partly the motivation for #124.

One possible way of addressing this is to be able to collect from a data source and generate a CSV using a command line utility, which optionally can just return the first n rows. This could be used when developing or tuning an Intake catalog entry, or developing Traject configuration, etc.

Given a catalog and source the program should be able to output a CSV. Maybe it could work something like:

```
$ bin/harvest <catalog name> <source name>

options: 
  --output                write output to file path
  --limit LIMIT           limit to the first n rows
```

**Comment by edsu** [comment]
I learned that intake has [a pretty nice CLI program](https://intake.readthedocs.io/en/latest/tools.html#intake-client) for seeing what catalog sources are there, validating and even running them. 

```bash
$ intake get catalogs/bodleian.yaml turkish
                                                  id  ...                                           contents
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/a...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/2...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/a...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/9...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/2...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/e...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/6...  ...                                                NaN
0  https://iiif.bodleian.ox.ac.uk/iiif/manifest/c...  ...  [Persian ghazals (ff. 1b-16b). Nesimi, Dīvān-i...

[8 rows x 30 columns]
```

There are two wrinkles:

1. The catalog driver needs to be more explicit in the YAML for intake to discover it:

```
driver: dlme_airflow.drivers.iiif_json:IiifJsonSource
```

instead of:

```
driver: iiif_json
```

This is because we rely on airflow to register these, and the intake CLI utility runs independently of airflow. Of course it wouldn't be too hard to make the driver declaration more explicit.

2. The other problem is that it doesn't seem to output the CSV, but the string representation of the DataFrame. Maybe that's something we could submit a patch for?

3. There doesn't seem to be a way of quitting early, so the whole harvest needs to run. But maybe that wouldn't be so bad if it's just one source within the provider?

**Comment by jacobthill** [comment]
I think 3 will be an issue. Unfortunately, some collections are really large 20k+ records that would have to run all the way through to see how they did.

**Comment by jacobthill** [comment]
Is there an easy way to pass in a few records via the catalogs (like we do for providers with multiple csv files) for the iiif_json and oai_xml drivers? If so, that might be enough

**Comment by edsu** [comment]
Maybe we can give #212 works and iterate on it? We could definitely adjust our custom drivers to have the ability to quit early. But it would be harder with the core drivers like csv unless we subclass them.

**Comment by jacobthill** [comment]
Sounds good, I think csv sources aren't a concern. They tend to harvest really quickly since its only making one http request per file and we have the option of only putting one file in the catalog.
