### ISSUE TITLE
Add command line option for post harvest tasks

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#247]
As a data manager, I use the command line intake option regularly to test airflow catalog configurations, get sample data for traject config testing, etc. When data providers have a post harvest task, the command line will not trigger that task. For example, QNL has a post harvest task to merge equivalent Arabic and English records into a single csv row. It is useful to trigger a post harvest task when one exists, so that the sample data retrieved matches what Airflow will output. It would be ideal to amend the `bin\get` command line tool with a post harvest flag to also trigger any post harvest tasks. e.g.

**Comment by aaron-collier** [comment]
Complete.
