### ISSUE TITLE
Configure "wait" for larger providers

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#248]
In #235 we now have the ability to sleep between requests in the OAI driver. We need to add sleep configurations to the following:
 
- [X] QNL
- [ ] AUB
- [ ] AUC
- [ ] Bodleian

**Comment by edsu** [comment]
Note, the current `wait: n` configuration support is only implemented in the `OaiXmlSource` driver. We would need another issue to add it for `IiifJsonSource` if you want to use it with `iiif_json` driver.

**Comment by jacobthill** [comment]
Thanks for pointing that out @edsu. Yes I think we will need it. I am seeing some connection issues with other collections, several of them use the `iiif_json` driver, but also I can foresee all of the drivers potentially needing this. Would it make sense to move this code to a high level like a utility that all drivers can access?

**Comment by edsu** [comment]
I recommend we close this ticket and open specific issues w/ log messages about problems we are encountering.
