### ISSUE TITLE
iiif_json driver not working for Princeton

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#283]
Princeton values are arrays and the iiif_json driver appends them to a list resulting in double brackets when the values are converted to csv e.g. `[['1933']]`

Some fields are multilingual with a key, value pair where the iiif_json driver is expecting only a value so we get `[[{'@language': 'ara-arab', '@value': 'محمود فريد'}]]` in the output. 

All three Princeton collections have these problems. It is unclear how common this might be but we might see this in other collections and perhaps we should adjust our driver so that it doesn't assume only string values in the metadata.

**Comment by aaron-collier** [comment]
@jacobthill this output should be fine, we need to make sure that `parse_csv` in transform is the first macro after the column selector. I'll take a look at those configs and run through some tests.

**Comment by jacobthill** [comment]
I'm not positive but I don't think this will solve the issue. I'm using parse_csv which will turn `[['1933']]` into `['1933']` if I understand correctly but it will still be an array what the first value is "['1933']" not an array where the first value is "1933". Also how do we deal with these values `[[{'@language': 'ara-arab', '@value': 'محمود فريد'}]]`?
