### ISSUE TITLE
Update ETL pipeline to post results URL to API

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme-airflow#342]
Current, TransformResults depends on the /transform_results route being subscribed to SNS message queue.  Since we are decoupling from SNS, we are need to post the transform result JSON to the endpoint directly from airflow.

(https://github.com/sul-dlss/dlme/blob/00403e9e39fe9f0bb6294f1b3ded28e52f39bced/app/controllers/transform_results_controller.rb) a

**Comment by thatbudakguy** [comment]
blocked on https://github.com/sul-dlss/dlme/issues/1683
