### ISSUE TITLE
Refactor transform validation for on prem deployment

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-airflow#366]
Refactor the existing transform validation code to read from the appropriate local harvest output and intermediate representation to verify that the correct number of records were transformed, if they don't match fail the ETL pipeline before indexing.

Part of this task should be to ensure that proper fail notifications are sent.

**Comment by edsu** [comment]
Do we know what "proper fail notifications" are yet or is this something to be figured out as part of this task?
