### ISSUE TITLE
Unicode byte decode error in Koç transform_validation task

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#416]
The koch transform_validation task is failing with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 7158: invalid continuation byte`

**Comment by aaron-collier** [comment]
@jacobthill this is passing transform validation for me (though reporting fails locally) - this is on dev: https://dlme-airflow-dev.stanford.edu/dags/koch/graph?execution_date=2023-07-13T00%3A17%3A51.927074%2B00%3A00

<img width="1585" alt="Screenshot 2023-07-12 at 5 32 24 PM" src="https://github.com/sul-dlss/dlme-airflow/assets/2294288/47e8806e-7630-42af-bbad-21881e33c249">

**Comment by jacobthill** [comment]
Nothing changed but it works now. I'm closing this and will re-open it if I encounter the issue again.
