### ISSUE TITLE
Write custom driver for Brooklyn Museum

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#451]
Brooklyn Museum requires us to [harvest a set of ids first](https://github.com/sul-dlss/dlme-harvest/blob/master/deprecated/harvest-scripts/brooklyn-ids.py), then [build urls for each record](https://github.com/sul-dlss/dlme-harvest/blob/master/deprecated/harvest-scripts/brooklyn-harvest.py). We need a custom driver for this. Or, alternatively, we could build a pre harvest task to fetch the ids and then use the `dlme_json` driver.

**Comment by aaron-collier** [comment]
I believe this was closed in https://github.com/sul-dlss/dlme-airflow/pull/454
