### ISSUE TITLE
Update package manager section in Readme

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#553]
We switched to `uv` for package management but the Readme still has instructions for `poetry`.  I have a PR [here](https://github.com/sul-dlss/dlme-airflow/pull/550) but when I follow those steps I still get this package not found error:

```
Traceback (most recent call last):
  File "/Users/jtim/Dropbox/Mac/Documents/DLSS/DLME/dlme-airflow/bin/get", line 11, in <module>
    from dlme_airflow.models.provider import Provider
ModuleNotFoundError: No module named 'dlme_airflow'
```

If I need to do something different, can you put that in the Readme. If I'm doing everything right but you also get this error, can you open another ticket to document it.

**Comment by edsu** [comment]
Thanks for doing this @jacobthill -- what do you run to generate that error?

**Comment by jacobthill** [comment]
@edsu `bin/get princeton al_madani > test.json`

**Comment by edsu** [comment]
Does `uv run bin/get princeton al_madani > test.json` work?
