### ISSUE TITLE
Need a solution for LOC IIIf

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#57]
The iiif_driver does not work for the LOC manifests. They follow a different format and don't return an iterable object with links to item level manifests: https://www.loc.gov/collections/abdul-hamid-ii-books/?c=100&fo=json

I'm not sure if this is a valid format that other institutions will also use or if we should treat this as a non-standard implementation and come up with a custom solution.

Needs some investigation, may be able to get it to work with out IIIF driver.

**Comment by edsu** [comment]
I can work on this once #51 is merged in.
