### ISSUE TITLE
Add instructions for downloading airflow exported data from AWS

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#94]
Trying to download airflow data from dev e.g. `curl -O https://dlme-metadata-dev.s3.us-west-2.amazonaws.com/metadata/bodleian/arabic/data.csv` results in a .csv file with this text: 

```<?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>ZJZFCZR0Q945EWH6</RequestId><HostId>ICcfYNBCbznhhtSdtbA+Npi53Wvgu9cy5zimCXJKQRIjwnkqsbYaVNbwyOybIST7XeZiC58fwEM=</HostId></Error>.```

So looks like a permissions problem when i try to download the file. This is currently blocking me from revising the Bodleian traject mappings, since I need that data locally to do so.

**Comment by jacobthill** [comment]
Ok, nevermind, new problem. I opened the file that I downloaded and it contains this ```<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>ZJZFCZR0Q945EWH6</RequestId><HostId>ICcfYNBCbznhhtSdtbA+Npi53Wvgu9cy5zimCXJKQRIjwnkqsbYaVNbwyOybIST7XeZiC58fwEM=</HostId></Error>```.

So looks like a permissions problem when i try to download the file.

**Comment by aaron-collier** [comment]
The above curl command will not work because the S3 bucket has limited access. This requires using the aws CLI for copying from S3.

**Comment by aaron-collier** [comment]
This is in the README.
