### ISSUE TITLE
Add step to remove duplicates to harvest dag

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#96]
Since all harvested records are written to a csv file, it makes sense to add a step to delete any duplicate rows from that csv file. This will prevent encountering error when trying to load duplicate records in the web app. Pandas drop_duplicates will work well for this https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html

There is a good chance that we will encounter duplicate records from different collections from the same provider e.g. the same record may appear in Bodleian Arabic and Bodleian Persian (it is quite common for Manuscripts to be written in two languages).  Given that, all csv files would need to be merged before duplicate rows are dropped.

Ideally the duplicate records could be captured for reporting to data providers, the id field and the url to the resource.

To make drop_duplicates work with and preserve seperate csv files per collection will need to merge data frames will keeping track of each individual dataframe e.g. https://stackoverflow.com/questions/62519791/finding-duplicates-in-two-dataframes-and-removing-the-duplicates-from-one-datafr

**Comment by aaron-collier** [comment]
Fixed in #68
