### ISSUE TITLE
Configuring provider dags in the main catalog.yaml file results in None being passed downstream 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#98]
Configuring data providers in the main catalog plus collections in a separate catalog (e.g. as in bodleian) works but when the provider is configured only in `catalog.yaml` I get dags with None in the name since no collection level key exists. I confirmed this is the issue by moving ifpo configurations into a separate file and adding a collection level key.
<img width="1451" alt="Screen Shot 2022-02-16 at 3 16 07 PM" src="https://user-images.githubusercontent.com/37662787/154355486-b001a200-e008-46f4-94d1-7217c679b08e.png">

**Comment by jmartin-sul** [comment]
after discussing this with @aaron-collier and @jacobthill this morning, we've decided to close this ticket as moot.  there are no longer any configs in this state, and we don't anticipate moving back to having more configuration inline in `catalog.yaml`, as that file is already getting large, so keeping provider specific configs split out into their own files should keep things more readable.
